baseURL = "https://yoooo.fun/"
title = "Aurora"
languageCode = "en-us"
footnoteReturnLinkContents = "â†©"
theme = ["github.com/miiiku/hugo-theme-kagome"]
paginate = 7
copyright = "Â© Since 2022 <a href=\"https://yoooo.fun\">Mystic</a>."
hasCJKLanguage = true
googleAnalytics = ""

[privacy]
[privacy.disqus]
disable = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# URLæ ¼å¼
[permalinks]
posts = "/:section/:year:month:day:15:04/"

# ä½œè€…ä¿¡æ¯
[author]
name = "Mystic"
email = "215104920@qq.com"
description = "To infinity and beyond"
avatar = "https://www.gravatar.com/avatar/8c115c6bc6688216bed0f053c506ff58?s=200&r=g&d=retro"

# èœå•/å¯¼èˆªæ 
[menu]
# é¡¶éƒ¨å¯¼èˆªæ 
[[menu.main]]
identifier = "/"
name = "ğŸ  HOME"
title = "HOME"
url = "/"
weight = 1
[[menu.main]]
identifier = "/posts"
name = "ğŸ—‚ï¸ POSTS"
title = "POSTS"
url = "/posts"
weight = 2
[[menu.main]]
identifier = "/about"
name = "ğŸ˜ˆ ABOUT"
title = "ABOUT"
url = "/about"
weight = 3
[[menu.main]]
identifier = "/link"
name = "ğŸ”— LINK"
title = "LINK"
url = "/link"
weight = 4

# åº•éƒ¨ç¤¾äº¤å›¾æ ‡
[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/pplmx"
weight = 1

# ä¸»é¢˜ç›¸å…³é…ç½®é¡¹
[params]
keywords = ["yoooo.fun", "caoyu.info", "hugo", "blog", "ä¸ªäººåšå®¢", "ä¸»é¢˜"]
description = "To infinity and beyond"
mainSections = ["posts"]
toc_show_len = 300

[params.analytics]
baidu = ""

[params.widget]
articles_count = 6
categories_count = 6
tags_count = 12

[params.aplayer]
theme = "#b7daff"
autoplay = false
loop = "none"
mutex = true

[params.dplayer]
theme = "#b7daff"
autoplay = false
loop = false
mutex = true
