# é¡¶éƒ¨å¯¼èˆªæ 
[[main]]
identifier = "/"
name = "ğŸ  HOME"
title = "HOME"
url = "/"
weight = 1

[[main]]
identifier = "/posts"
name = "ğŸ—‚ï¸ POSTS"
title = "POSTS"
url = "/posts"
weight = 2

[[main]]
identifier = "/about"
name = "ğŸ˜ˆ ABOUT"
title = "ABOUT"
url = "/about"
weight = 3

[[main]]
identifier = "/link"
name = "ğŸ”— LINK"
title = "LINK"
url = "/link"
weight = 4

# åº•éƒ¨ç¤¾äº¤å›¾æ ‡
[[social]]
identifier = "github"
name = "github"
url = "https://github.com/pplmx"
weight = 1
